### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by uyitroa** [notarisj/YouTube-AutoSkip#3]
## Issue description
This extension had been working for a few months now, but I noticed that it just stopped working today. I'm using Safari 16.3, macOS 13.2. It doesn't mute nor speeding up ad anymore.

**Comment by uyitroa** [comment]
After checking, I believe that 
```js
var adOverlay = document.querySelector('.ytp-ad-player-overlay');
``` 
is `null` even though there is an ad in the video.

However, I noticed that `.ytp-ad-player-overlay-layout` is not null so maybe we could change the line to
```js
var adOverlay = document.querySelector('.ytp-ad-player-overlay-layout');
```

**Comment by WeiChihChern** [comment]
Yeah, I think youtube has changed something that makes the extension fails.  

Have you tried your modification and see if it works?

**Comment by notarisj** [comment]
I just noticed this issue today. I will be testing it, and if it does not cover all cases, I will try to fix it with a wildcard to be less prone to YouTube changes and create a new release. Thanks for the contribution!
